eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
spring:
  application:
    name: accounts
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:bank}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root@123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bank
kafka:
  topics:
    account-created: account-created-topic