spring:
  profiles: kafka
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      spring.json.add.type.headers: false
kafka:
  default:
    replication-factor: 1
    partitions: 3
    min-insync-replicas: 1
  topics:
    account-created: account-created-topic